//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class controles
    {
        public long id { get; set; }
        public string control { get; set; }
        public string idioma { get; set; }
        public Nullable<int> id_idioma { get; set; }
        public Nullable<int> id_formulario { get; set; }
        public string texto { get; set; }
    }
}
