//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ferronetContext : DbContext
    {
        public ferronetContext()
            : base("name=ferronetContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<controles> controles { get; set; }
        public virtual DbSet<formulario> formulario { get; set; }
        public virtual DbSet<idioma> idioma { get; set; }
        public virtual DbSet<autenticacion> autenticacion { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<detalle_pedido> detalle_pedido { get; set; }
        public virtual DbSet<detalle_venta> detalle_venta { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<producto_subsede> producto_subsede { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<sede> sede { get; set; }
        public virtual DbSet<sub_sede> sub_sede { get; set; }
        public virtual DbSet<token_recuperacion_usuario> token_recuperacion_usuario { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
    }
}
