//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public long id { get; set; }
        public string tipo_entrega { get; set; }
        public string direccion { get; set; }
        public Nullable<int> valor_total { get; set; }
        public Nullable<int> id_subsede { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string session { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
    }
}
