//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_sede
    {
        public long id { get; set; }
        public string nombre { get; set; }
        public string ubicacion { get; set; }
        public Nullable<int> id_admin { get; set; }
        public Nullable<int> id_cajero { get; set; }
        public Nullable<int> id_sede { get; set; }
        public string session { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
    }
}
